### ISSUE TITLE
DebugMode settings not working

### ISSUE THREAD

**Issue by XiCynx** [xUnholy/Ethereal-App#5]
Setting the DebugMode in UserSettings.settings to True or False does not change the Debug mode.

**Comment by Tukurai** [comment]
Ill pick this up in the morning.
On Aug 23, 2016 11:33 PM, XiCynx <notifications@github.com> wrote:Setting the DebugMode in UserSettings.settings to True or False does not change the Debug mode.

**Comment by Tukurai** [comment]
This works properly. I'm able to change the settings and it will read it from the file, or from the defaults. Can you post steps to reproduce this issue you had?
